Ek
mohammedek/homemade_loc_tracking_app pull request #1
Opened 2023-01-12 21:01 UTC by mohammedek

**create Account Screen**
! icon issues
! mobile digit shower issue (still)
! made changes in gap between widgets to avoid bottom overflow

2023-01-14 08:04 UTC, Ashbuhrz commented on lib/app/screens/create_account_screen.dart
> +                const SizedBox(width: 10),
use Gap
`Gap(10)`

2023-01-14 08:35 UTC, Ashbuhrz requested changes
Also change all the empty SizedBox to Gap. 
Change Explicit TextStyle to Theme.of method

2023-01-14 08:35 UTC, Ashbuhrz commented on lib/app/screens/create_account_screen.dart
> +                const SizedBox(width: 10),
Here

2023-01-14 08:35 UTC, Ashbuhrz commented on lib/app/screens/create_account_screen.dart
> +                const SizedBox(width: 10),
use Gap
Gap(10)

2023-01-14 08:35 UTC, Ashbuhrz commented on lib/app/screens/create_account_screen.dart
> +                    text_color: deepOrange,
Use class instead of just global variables. So that we can understand which category it belongs to.

2023-01-14 08:35 UTC, Ashbuhrz commented on lib/app/screens/create_account_screen.dart
> +                    text_color: deepOrange,
AppColors.deepOrange

2023-01-14 08:35 UTC, Ashbuhrz commented on lib/app/screens/create_chef_pages/create_chef_screen_2.dart
> +                            child: SvgPicture.asset(Assets.images.svg.recatnagleDotted.path)
Why using like this??
Use like this `Assets.images.svg.recatnagleDotted.image`, instead of `SvgPicture.asset(Assets.images.svg.recatnagleDotted.path)`

2023-01-14 08:35 UTC, Ashbuhrz commented on lib/app/screens/create_chef_pages/create_chef_screen_2.dart
> +                      // DottedBorder(
Remove this dead code, if not needed in future

2023-01-14 08:35 UTC, Ashbuhrz commented on lib/app/screens/create_chef_pages/create_chef_screens_3.dart
> +  bool agree = false;
Always use is before a boolean variable.
like,
`bool isAgree = false;`

2023-01-14 08:35 UTC, Ashbuhrz commented on lib/app/screens/create_chef_pages/create_chef_screens_3.dart
> +}
Why this

2023-01-14 08:35 UTC, Ashbuhrz commented on lib/app/screens/create_chef_pages/create_chef_screens_3.dart
> +                          )),
Change this

2023-01-14 08:35 UTC, Ashbuhrz commented on lib/app/widgets/image_uploader_container.dart
> +             // color: Colors.deepOrange,
remove not needed

2023-01-14 08:35 UTC, Ashbuhrz commented on lib/app/widgets/otp_container.dart
> +// }
remove

2023-01-14 08:35 UTC, Ashbuhrz commented on lib/main.dart
> +      // LoginScreen()
??

2023-01-14 08:35 UTC, Ashbuhrz commented on pubspec.yaml
> +    - assets/images/png/document_write_logo.png
??

```
assets/images/png
assets/images/svg
```
is enough..
no need to explicitly mention each assets location.
You can just mention the location folder.
Also you can use
`assets/images` that's it

2023-01-14 08:37 UTC, Ashbuhrz requested changes

2023-01-14 08:37 UTC, Ashbuhrz commented on lib/app/utilities/constants.dart
>  const String Privacy = "Privacy policy";
No need of this

2023-01-14 08:37 UTC, Ashbuhrz commented on lib/app/utilities/constants.dart
> +const String h1_Crt_text2 = "Stay Healthy Always";
No need to do this.

2023-01-14 08:50 UTC, mohammedek commented on lib/main.dart
> +      // LoginScreen()
Screen wise loading emulator, commented used

2023-01-14 09:02 UTC, mohammedek commented on lib/app/screens/create_chef_pages/create_chef_screen_2.dart
> +                            child: SvgPicture.asset(Assets.images.svg.recatnagleDotted.path)
Svg not loading when calling like that

2023-01-16 08:49 UTC, Ashbuhrz approved these changes

2023-01-16 08:49 UTC, merged